-- Generirano iz data/words.json (node scripts/generate-seed.mjs).
-- Ne uređivati ručno; uredi words.json pa ponovno pokreni skriptu.
-- Primjena:  npx wrangler d1 execute spy-words --remote --file=./seed.sql
--
-- "OR IGNORE" znači da ponovno pokretanje ne stvara duplikate i ne dira
-- riječi koje si u međuvremenu dodao ili obrisao kroz aplikaciju.

INSERT OR IGNORE INTO words (text, normalized, category) VALUES
  ('Plaža', 'plaža', 'Mjesta'),
  ('Bolnica', 'bolnica', 'Mjesta'),
  ('Zrakoplov', 'zrakoplov', 'Mjesta'),
  ('Škola', 'škola', 'Mjesta'),
  ('Kazalište', 'kazalište', 'Mjesta'),
  ('Podmornica', 'podmornica', 'Mjesta'),
  ('Svemirska postaja', 'svemirska postaja', 'Mjesta'),
  ('Nogometni stadion', 'nogometni stadion', 'Mjesta'),
  ('Restoran', 'restoran', 'Mjesta'),
  ('Vlak', 'vlak', 'Mjesta'),
  ('Banka', 'banka', 'Mjesta'),
  ('Cirkus', 'cirkus', 'Mjesta'),
  ('Zoološki vrt', 'zoološki vrt', 'Mjesta'),
  ('Policijska postaja', 'policijska postaja', 'Mjesta'),
  ('Skijalište', 'skijalište', 'Mjesta'),
  ('Knjižnica', 'knjižnica', 'Mjesta'),
  ('Vatrogasni dom', 'vatrogasni dom', 'Mjesta'),
  ('Kino', 'kino', 'Mjesta'),
  ('Tržnica', 'tržnica', 'Mjesta'),
  ('Hotel', 'hotel', 'Mjesta'),
  ('Vojarna', 'vojarna', 'Mjesta'),
  ('Svjetionik', 'svjetionik', 'Mjesta'),
  ('Liječnik', 'liječnik', 'Zanimanja'),
  ('Učiteljica', 'učiteljica', 'Zanimanja'),
  ('Vatrogasac', 'vatrogasac', 'Zanimanja'),
  ('Policajac', 'policajac', 'Zanimanja'),
  ('Kuhar', 'kuhar', 'Zanimanja'),
  ('Pilot', 'pilot', 'Zanimanja'),
  ('Glumac', 'glumac', 'Zanimanja'),
  ('Vozač autobusa', 'vozač autobusa', 'Zanimanja'),
  ('Frizer', 'frizer', 'Zanimanja'),
  ('Novinar', 'novinar', 'Zanimanja'),
  ('Zubar', 'zubar', 'Zanimanja'),
  ('Građevinar', 'građevinar', 'Zanimanja'),
  ('Ribar', 'ribar', 'Zanimanja'),
  ('Sudac', 'sudac', 'Zanimanja'),
  ('Kišobran', 'kišobran', 'Predmeti'),
  ('Naočale', 'naočale', 'Predmeti'),
  ('Ključevi', 'ključevi', 'Predmeti'),
  ('Ručni sat', 'ručni sat', 'Predmeti'),
  ('Ruksak', 'ruksak', 'Predmeti'),
  ('Svijeća', 'svijeća', 'Predmeti'),
  ('Ogledalo', 'ogledalo', 'Predmeti'),
  ('Škare', 'škare', 'Predmeti'),
  ('Jastuk', 'jastuk', 'Predmeti'),
  ('Bicikl', 'bicikl', 'Predmeti'),
  ('Gitara', 'gitara', 'Predmeti'),
  ('Fotoaparat', 'fotoaparat', 'Predmeti'),
  ('Četkica za zube', 'četkica za zube', 'Predmeti'),
  ('Šalica', 'šalica', 'Predmeti');
